const fs = require('fs');

const loreData = {
"001": "Created for the launch of the PS5, this ultra-rare promotional Dunk features Travis Scott's signature reverse Swoosh and PlayStation branding. Only five pairs were given away to the public via a raffle.",
"002": "Celebrating the beloved Cartoon Network series, this Bubbles-themed SB Dunk features a textured yellow upper, blue accents, and lenticular eyes on the heel tab.",
"004": "Part of the 'Dunk vs AF1' pack, this collaboration with UNDEFEATED flips classic Air Force 1 colorways onto the Dunk silhouette, utilizing premium materials and faux snakeskin.",
"005": "A clean and essential two-tone colorway. The 'Grey Fog' offers a more subtle, muted alternative to the ubiquitous Panda Dunk, becoming a massive staple in streetwear.",
"006": "A nod to the Japanese exclusive Co.Jp releases, this 'Wizard' colorway brings back a retro aesthetic with rich textures and striking purple hues.",
"007": "A spooky, retro-themed Dunk inspired by the Upside Down of Stranger Things. Features distressed materials and hidden details beneath the upper.",
"008": "A stealthy, all-black iteration of the classic Dunk Low. Constructed with mixed materials for durability and a monochromatic aesthetic.",
"010": "A bizarre, textured creation from Cynthia Lu's CPFM, featuring a Grinch-like shaggy upper and mismatched sole units.",
"011": "Released as part of a Halloween collection, this shoe features monster-inspired green hues, metallic silver Swooshes resembling neck bolts, and stitch details.",
"013": "A gamer-focused release celebrating the League of Legends World Championship, featuring iridescent details and LPL branding.",
"014": "Inspired by the Japanese festival of Setsubun (bean-throwing festival), featuring cracked leather, demon motifs on the heel, and roasted bean colors.",
"015": "Legendary graffiti artist Futura brings his signature abstract art style to the SB Dunk, featuring custom artwork panels and translucent soles.",
"016": "Part of the vintage-inspired Athletic Department collection, featuring aged midsoles and collegiate deep green accents.",
"017": "A versatile lifestyle colorway blending dark navy overlays with smoke grey bases, perfect for everyday rotation.",
"018": "A Lunar New Year special edition featuring dragon-scale textures and festive red accents to celebrate the zodiac year.",
"019": "A retro of the classic 2004 release, bringing back the metallic silver mesh and blue Swoosh that made the original a cult classic.",
"020": "Commemorating the Year of the Snake with faux snakeskin panels and premium earth-toned leather overlays.",
"021": "A flipped version of the ultra-popular Panda Dunk, using white on the overlays and black on the underlays for a fresh twist.",
"022": "Virgil Abloh's amalgamation of the P-6000 and the Dunk, featuring rubberized accents and a vibrant green strike outline.",
"023": "Part of Nike's Move to Zero initiative, this eco-friendly Dunk is made with at least 20% recycled materials by weight.",
"024": "Representing the toughest Powerpuff Girl, this SB features a striking green and black colorway with Buttercup's intense glare on the heel.",
"025": "A highly exclusive Player Exclusive made for the Oregon Ducks, mashing up various eras of the university's uniform history.",
"026": "Another wild, mossy release from CPFM, featuring long-hair suede and mismatched details in a striking blue hue.",
"027": "Designed by Girls Don't Cry founder Verdy, inspired by his colorful, fluffy monster character 'Visty', featuring pastel hues and faux fur.",
"028": "A re-release of the original 1985 'Be True to Your School' colorway honoring the University of Kentucky Wildcats.",
"029": "Inspired by early 2000s Japan-exclusive releases, this Union collaboration features a tear-away ripstop upper revealing premium leather underneath.",
"030": "A clean, collegiate-style colorway featuring a deep Valerian Blue over a white base with subtle red accents on the branding.",
"031": "One of the most popular women's exclusive colorways of the 2020s, featuring rich chocolate brown overlays that pair perfectly with neutral outfits.",
"032": "A core skate shop collaboration with Limosine, utilizing rugged materials and subtle football-inspired textures.",
"033": "Continuing the long-standing partnership, this Supreme SB Dunk features premium materials and the iconic world famous branding.",
"034": "A tribute to the late Sandy Bodecker, the godfather of Nike SB. This shoe recreates the legendary cut-up eBay Charity Dunk.",
"035": "A playful crossover with the beloved Mexican soda brand, featuring tear-away canvas panels that reveal a bright orange suede underneath.",
"036": "A rumored retro of the legendary 2005 UNDFTD Jordan 4, the first-ever exclusive sneaker collaboration for the Jordan Brand, originally limited to 72 pairs.",
"037": "Features an unreleased 'Rare Air' sample design concept, highlighted by velcro tongue patches and distinct white lettering.",
"038": "A women's exclusive utilizing heavily washed and distressed denim materials across the iconic Jordan 4 upper.",
"039": "A highly anticipated re-release of the beloved all-black nubuck colorway, originally inspired by Michael Jordan's predatory nickname.",
"040": "The return of a masterpiece. Worn by MJ during the 1989 season and famous for its appearance in Do the Right Thing, complete with Nike Air branding.",
"041": "Following the massive success of the Pine Green edition, this skate-ready Jordan 4 features a reshaped toe box and flexible plastic components.",
"042": "An earth-toned release that continues the trend of neutral, highly wearable Jordan 4 colorways.",
"043": "BMX star Nigel Sylvester's take on the Jordan 4, featuring heavily distressed details mimicking the scuffs from riding a bike.",
"044": "A mystery entry in the archive, representing a highly guarded release date for an upcoming Jordan silhouette.",
"045": "Reversing the classic Thunder color block, this 2024 release swaps yellow for crisp white against a black nubuck upper.",
"046": "Replacing the traditional nubuck of the 1989 classic with premium tumbled leather, reimagining the shoe MJ wore for 'The Shot'.",
"047": "The long-awaited return of the 1989 OG colorway, featuring the correct off-white upper and original Nike Air branding on the heel.",
"048": "The grade-school sizing of the stealthy all-black classic, ensuring the next generation can wear the 'Black Cat'.",
"049": "James Whitner's boutique delivers another luxurious collaboration, featuring premium materials, quilted linings, and subtle storytelling.",
"050": "A spin on the 2006 'Thunder' colorway, replacing the tour yellow accents with vibrant crimson red.",
"051": "A monumental 2023 release that retooled the Jordan 4 for skateboarding, instantly becoming one of the most celebrated sneakers of the decade.",
"052": "Inspired by the 2024 Paris Olympics, this tonal grey release mimics the cobblestone streets of the French capital.",
"053": "The definitive retro of the shoe Michael Jordan wore when he hit 'The Shot' over Craig Ehlo in the 1989 Playoffs.",
"054": "Part of AMM's six-shoe anniversary collection, utilizing premium muted tones and luxurious interior details.",
"055": "A retro of the 2013 classic from the 'Fear Pack', inspired by MJ's quote: 'I am scared of what I won't become.'",
"056": "A flawless recreation of the 1989 original, complete with Nike Air on the heel and the vibrant Fire Red accents.",
"057": "A vibrant pink suede women's exclusive, featuring speckled grey wings that contrast beautifully with the bright upper.",
"058": "Bringing back the 2006 LS (Lifestyle) release, known for its striking black and yellow color-blocking.",
"059": "Swapping traditional nubuck for a durable canvas upper, offering a rugged, workwear-inspired take on the silhouette.",
"060": "Virgil Abloh's deconstructed masterpiece. Originally debuted at his 'Figures of Speech' exhibit, it became one of the most coveted women's sneakers ever.",
"061": "A return of the bold 2013 colorway, featuring a vibrant red suede upper that completely flips the script on Chicago colors.",
"062": "Paying homage to Michael Jordan's UNC days, this release utilizes premium blue suede and classic cement speckling.",
"063": "A massive mainstream hit from 2022. It uses the exact color-blocking of the OG Military Blue but replaces the blue with black.",
"064": "The first-ever retro of the legendary 2006 online-exclusive, featuring a bright Tour Yellow nubuck upper.",
"065": "A clever twist on the OG White Cement, replacing the grey speckled areas with a vibrant fire red.",
"066": "Utilizing the classic 'White Cement' color blocking but replacing the black and red accents with deep navy blue.",
"067": "An all-white release originally dropped in 2010 to celebrate 25 years of the Air Jordan lineage.",
"068": "Featuring a muted purple upper, a metallic pin on the collar, and a quote hidden behind the heel tab: 'It is not about the shoes, it is about where you are going.'",
"069": "A clean, summer-ready colorway from 2021 that applies the speckled grey aesthetic to an all-white tumbled leather base.",
"070": "An earthy, pre-distressed colorway that drew heavy comparisons to Travis Scott's unreleased F&F Olive 4s.",
"071": "The grade-school sizing of the legendary 1989 classic, bringing Nike Air branding to smaller feet.",
"072": "The shoe that catapulted the 2002R to modern stardom. Designed by Yue Wu, it features jagged, deconstructed suede panels meant to look like they've been worn and torn.",
"073": "A stealthy, dark grey addition to the highly successful 'Refined Future' collection, known for its raw edges.",
"074": "Not to be confused with Jordan, this dark iteration of the futuristic 9060 silhouette utilizes heavy mesh and premium suedes.",
"075": "Embodying the Y2K runner aesthetic, this release relies on aggressive silver overlays and a dark mesh base.",
"076": "A revival of an obscure archival runner, brought back with modern tech and aggressive metallic styling.",
"077": "An ultra-premium execution of the chunky 9060, using hairy suede and muted off-white tones.",
"078": "A perfect blend of vintage and futuristic, using a cream midsole to simulate age beneath shiny silver uppers.",
"079": "An alternate tooling of the 1906, offering a more streamlined, stealthy all-black aesthetic.",
"080": "Originally released in 1996, the 850 was the first New Balance shoe to remove the iconic N logo from the side profile.",
"081": "A rugged, stealthy take on the Y2K-inspired silhouette, utilizing heavy suede panels across the entire upper.",
"082": "The ultimate 'dad shoe' of the 2020s, offering massive comfort and a retro 90s aesthetic at an accessible price point.",
"083": "Leaning heavily into 2000s maximalism, this colorway combines bright silver and gold accents over a white mesh base.",
"084": "A clean, white and cream version of Yue Wu's 'Refined Future' pack, featuring the signature jagged edges.",
"085": "A vibrant, lifestyle-focused iteration of the tech runner, utilizing bright pink accents for a playful look.",
"086": "A moody, greyscale approach to the 9060, highlighting the extreme proportions of the ABZORB midsole.",
"087": "A sleek, dark colorway of the recently revived late-90s silhouette, favored for its chunky, wavy upper panels.",
"088": "A cool-toned, blue-grey version of the futuristic runner, offering a frosty aesthetic with premium suede.",
"089": "Combining Y2K runner vibes with rich blue accents, making it a standout in the modern tech-runner craze.",
"090": "A massive collaboration blending BAPE's iconic ABC camo and shark tooth motifs with the comfortable 2002R runner.",
"091": "An everyday staple utilizing the highly comfortable N-ERGY sole unit paired with a durable black suede upper.",
"092": "A loafer iteration of the 1906! Blending high-tech running soles with a slip-on loafer upper, creating a bizarre but highly popular fashion fusion.",
"093": "Bringing the jagged, torn 'Refined Future' aesthetic to the 1906 silhouette in a stealthy all-black execution.",
"094": "An outdoor-inspired colorway of the chunky 1999 runner, blending rich green suedes with a white mesh base.",
"095": "Steven Smith's 1989 basketball oxford, revived by Aimé Leon Dore, presented here in a clean, neutral grey and white GR colorway.",
"096": "A special edition of the jagged 'Refined Future' pack, featuring muted tones meant to celebrate the changing of the zodiac calendar.",
"097": "A highly technical looking colorway, leaning on dark metallic accents over a black mesh base.",
"098": "An incredibly popular, lightweight lifestyle runner that dominated global street style throughout the early 2020s.",
"099": "A striking colorway that pops dark bases with vibrant purple-pink 'Dragon Berry' accents on the N-Lock logo.",
"100": "A deep navy iteration of the deconstructed suede pack that took the sneaker world by storm.",
"101": "A pure homage to early 2000s running shoe aesthetics, complete with aggressive metallic overlays.",
"102": "A pristine, all-white application of the torn-suede aesthetic on the popular 1906 tech runner.",
"103": "An exclusive, earth-toned version of the Refined Future pack released specifically for European retailer size?.",
"104": "A masterclass in neutral toning, blending soft greys and creams on the retro-futuristic 9060 silhouette.",
"105": "A standard yet highly effective Y2K colorway, combining breathable black mesh with structured silver synthetic panels.",
"106": "A faithful retro of a niche early 2000s stability runner, featuring classic navy and grey New Balance blocking.",
"107": "A unique, fashion-forward release utilizing a washed, overdyed pink treatment on the suede upper.",
"108": "The fourth iteration of the legendary 990 series, refined for modern wear while keeping the absolute highest standard of US manufacturing.",
"109": "The standard-bearer of the modern Made in USA line, introducing FuelCell cushioning to the legendary 990 lineage.",
"110": "Widely considered the best of the 990 series. The v3 introduced a more aggressive, technical look while maintaining supreme comfort and domestic quality.",
"111": "Designed by ALD founder Teddy Santis for his Made in USA seasonal collection, featuring premium hairy suede and contrasting black midsoles.",
"112": "The quintessential stealth dad-shoe, favored by tech CEOs and streetwear enthusiasts alike for its unrivaled comfort and quality.",
"113": "Celebrating the Boston boutique's 15th anniversary, this earthy release features massive attention to detail, premium pigskin, and custom branding.",
"114": "The rapper/chef's first collaboration, featuring a wild, colorful mix of neon greens, blues, and browns that perfectly matches his chaotic energy.",
"115": "Bronson's second 990v6, taking a more wearable approach with rich blues, silver accents, and a gum sole.",
"116": "A slight variation on the classic grey v4, featuring a red tab on the tongue denoting its premium Made in USA status.",
"117": "A clean, simple execution of the v4, offering a durable black suede upper perfect for harsh weather wear.",
"118": "A highly limited iteration of Bronson's chaotic color palette, brought to life on the comfortable FuelCell sole.",
"119": "Part of Season 4 of Santis' direction, utilizing a moody grey and black scheme with white laces for heavy contrast.",
"120": "A bold seasonal drop combining earth-toned suedes with sharp, vibrant orange accents.",
"121": "A stunning use of color on the typically grey 990, wrapping the entire shoe in rich, premium purple suede.",
"122": "Swapping the usual grey for a rugged, wheat-like tan colorway that evokes classic work boots.",
"123": "Evoking classic collegiate colors, this Made in USA release blends deep forest green with golden yellow hits.",
"124": "A masterful, subtle shift from the standard grey, using lighter tones and premium mesh.",
"125": "The official name of Bronson's neon-green debut collab, instantly recognizable and highly sought after.",
"126": "A highly exclusive regional release celebrating the opening of the Paris Aimé Leon Dore flagship store.",
"127": "Part of a pack highlighting local community hubs, featuring vibrant red suedes and standard domestic craftsmanship.",
"128": "The Montreal design studio's masterclass in minimalism, selling out instantly and commanding massive resale prices due to its perfect shade of green.",
"129": "The stealth bomber of the v6 lineup, perfect for the hospitality industry or tech-wear fashion.",
"130": "Following up the Olive release, Justin Saunders applied a rich chocolate brown to the v3 with black accents.",
"131": "A vibrant, pinkish-orange take on the v6, breaking from New Balance's traditionally muted color palettes.",
"132": "A staple colorway in the NB catalog, offering a slightly more formal alternative to the classic grey.",
"133": "A highly refined, tonal beige colorway that perfectly fits the Aimé Leon Dore aesthetic.",
"134": "Focusing on deep, collegiate navy blue, accented by crisp white midsoles and silver N logos.",
"135": "One of the standout hits from Santis' Season 1, utilizing a striking purple suede over a navy mesh base.",
"136": "A bold, somewhat Joker-esque color palette executed with the highest quality domestic materials.",
"137": "Blending vibrant red suede with traditional grey mesh, creating a striking contrast.",
"138": "The 2019 update to the 990, known for its plastic power strap on the collar and a slightly more streamlined look.",
"139": "A highly wearable colorway combining a black base with tan heel accents, providing a subtle pop of contrast.",
"140": "Ronnie Fieg's homage to the legendary 1300JP colorway, ported over flawlessly to the 990v3 silhouette.",
"141": "The standard grey iteration of the v4, beloved by DMV residents and global fashion icons alike.",
"142": "Featuring a dark, earthy green tone, released exclusively through ALD before hitting broader New Balance channels.",
"143": "A soft, pastel approach to the highly technical v6, offering a refreshing spring aesthetic."
};

const filePath = 'src/data/products.ts';
let content = fs.readFileSync(filePath, 'utf8');

const regex = /"id":\s*"(\d+)",([\s\S]*?)"productUrl":\s*"([^"]+)"\s*\n\s*\}/g;

let modified = content.replace(regex, (match, id, middle, url) => {
  if (loreData[id]) {
    const specificLore = JSON.stringify(loreData[id]);
    return match.replace(/\}$/, `,\n    "lore": ${specificLore}\n  }`);
  }
  return match;
});

fs.writeFileSync(filePath, modified, 'utf8');
console.log('Successfully added specific lore to each shoe.');
